#!/bin/sh /etc/rc.common

USE_PROCD=1
START=21 # launch just after general networking
STOP=89 # stop just before general networking

start_service() {
	if [ ! -x /usr/sbin/ebpf-clat ]; then
		echo "Cannot find ebpf-clat" 1>&2
		return 1
	fi
	if [ ! -h /sys/class/net/br-client ]; then
		echo "Cannot find br-client" 1>&2
		return 2
	fi
	if [ ! -r /tmp/xlat_range6 ]; then
		echo "Cannot find config in /tmp/xlat_range6" 1>&2
		return 3
	fi

	ifaceindex="$(cat /sys/class/net/br-client/ifindex)"

	procd_open_instance
	procd_set_param command /usr/sbin/ebpf-clat "${ifaceindex}" "${ifaceindex}" "$(cat /tmp/xlat_range6)" "64:ff9b::"
	procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
	procd_set_param stdout 1 # TODO: remove this output
	procd_set_param stderr 1
	procd_close_instance
}
