need_string({ "parker", "config_server" })
need_string({ "parker", "config_pubkey" })
need_string_array_match({ "parker", "client_ntp_servers4" }, '^%d+%.%d+%.%d+%.%d+$', false)
need_string_array({'ntp_servers'})
need_number({ "mesh_vpn", "parker", "mtu" })
